language: node_js
node_js:
  - "14"
script:
  - npm install
  - npm test
  - nyc --reporter=text --reporter=lcov npm test  # Collect coverage
after_success:
  - npm run coveralls  # Send coverage data to Coveralls

