name: Coverage and Test Reporting

on:
  push:
    branches:
      - main  # Adjust for your main branch
  pull_request:
    branches:
      - main  # Adjust for your main branch

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.9.0'  # Adjust the version of Node.js if needed

    - name: Install dependencies
      run: npm install

    - name: Run tests with coverage
      run: npm run coverage

    - name: Report to Coveralls
      run: npm run coveralls
      env:
       COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}}
