name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.9.0'  # Use the appropriate Node.js version
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: |
          npx nyc --reporter=lcov --report-dir=coverage mocha --loader ts-node/register --require ts-node/register test/**/*.test.mjs

      - name: Upload coverage to Codecov (or other service)
        uses: codecov/codecov-action@v3
        with:
          file: coverage/lcov-report/lcov-report.json  # Adjust based on your coverage setup

